serviceAccount: projects/apple-news-db6d6/serviceAccounts/218389833235-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

#steps:
#  - name: 'python'
#    entrypoint: pip
#    args: ['install', '--upgrade', 'pip']
#
#  - name: 'python'
#    entrypoint: pip
#    args: ['install', '-r', 'requirements.txt', '--user']
#
#  - name: 'python'
#    entrypoint: python
#    args: ['main.py']

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - extract
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime= python310

