serviceAccount: $SERVICE_ACCOUNT
options:
  logging: CLOUD_LOGGING_ONLY

#steps:
#  - name: 'python'
#    entrypoint: pip
#    args: ['install', '--upgrade', 'pip']
#
#  - name: 'python'
#    entrypoint: pip
#    args: ['install', '-r', 'requirements.txt', '--user']
#
#  - name: 'python'
#    entrypoint: python
#    args: ['main.py']

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - extract
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=python310
  env:
  - 'API_URL = https://newsapi.org/v2/everything?q=apple'

